#!/usr/bin/env node
/**
 * Generates src/routes.generated.ts from the api folder.
 * Run: node scripts/gen-routes.mjs
 *
 * Routes in PUBLIC_ROUTES do not use authMiddleware. All other routes require auth.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const apiDir = path.join(__dirname, '../src/api');
const outFile = path.join(__dirname, '../src/routes.generated.ts');

const methods = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];

/** Routes where ALL methods are public (no auth) */
const PUBLIC_ROUTES = new Set([
  '/api/auth/login',
  '/api/auth/register',
  '/api/auth/send-otp',
  '/api/auth/verify-otp',
  '/api/auth/verify-email',
  '/api/board-class-subjects',
  '/api/registration/send-otp',
  '/api/registration/verify-otp',
  '/api/parent-registration/check-phone',
  '/api/parent-registration/save',
  '/api/teacher-registration/check-phone',
  '/api/teacher-registration/complete',
  '/api/teacher-registration/data',
  '/api/teacher-registration/exam/monitor',
  '/api/teacher-registration/exam',
  '/api/teacher-registration/exam/status',
  '/api/teacher-registration/save',
  '/api/teacher-registration/verify-access',
  '/api/cron/generate-schedules',
  '/api/cron/notifications',
  '/api/seed-admin',
  '/api/seed-staff',
  '/api/seed-masters',
  '/api/seed-topics',
  '/api/seed-cms-pages',
  '/api/seed-website-settings',
  '/api/seed-website-page-content',
  '/api/seed-job-positions',
  '/api/seed-documents',
  '/api/teachers/marketplace',
  '/api/teachers/:id',
  '/api/cms-pages/:slug',
  '/api/website/landing',
  '/api/website/page-content',
  '/api/website/team',
  '/api/website/settings',
  '/api/website/job-positions',
  '/api/website/job-applications',
  '/api/website/contact-submissions',
  '/api/geocode/suggest',
]);

/** Specific path:method combinations that are public (for mixed auth routes) */
const PUBLIC_ROUTE_METHODS = new Set(['/api/masters:GET']);

/** Routes handled manually (e.g. multipart file upload) - exclude from gen-routes */
const SKIP_ROUTES = new Set(['/api/website/job-applications', '/api/admin/job-positions/:id/jd']);

function findRouteFiles(dir, base = '') {
  const results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      results.push(...findRouteFiles(fullPath, relPath));
    } else if (entry.name === 'route.ts') {
      const routePath = '/api/' + relPath.replace(/\/route\.ts$/, '').replace(/\[([^\]]+)\]/g, ':$1');
      results.push({ routePath, filePath: fullPath });
    }
  }
  return results;
}

function getExportedMethods(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const found = [];
  for (const m of methods) {
    if (new RegExp(`export\\s+async\\s+function\\s+${m}\\s*\\(`).test(content)) found.push(m);
  }
  return found;
}

function toVarName(routePath) {
  return routePath.replace(/\//g, '_').replace(/[^a-z0-9_]/g, '') || 'root';
}

const routeFiles = findRouteFiles(apiDir);
const imports = [];
const registrations = [];

routeFiles.forEach(({ routePath, filePath }) => {
  if (SKIP_ROUTES.has(routePath)) return;
  const exported = getExportedMethods(filePath);
  if (exported.length === 0) return;
  const relPath = path.relative(path.join(__dirname, '../src'), filePath).replace(/\.ts$/, '.js').replace(/\\/g, '/');
  const prefix = toVarName(routePath);
  const importSpecs = exported.map((m) => `${m} as ${m}_${prefix}`).join(', ');
  imports.push(`import { ${importSpecs} } from './${relPath}';`);
  exported.forEach((m) => {
    const useAuth =
      !PUBLIC_ROUTES.has(routePath) && !PUBLIC_ROUTE_METHODS.has(`${routePath}:${m}`);
    const mw = useAuth ? 'authMiddleware, ' : '';
    registrations.push({ routePath, method: m, line: `  app.${m.toLowerCase()}('${routePath}', ${mw}adaptNextRoute(${m}_${prefix}));` });
  });
});

// Sort so literal paths (e.g. /staff/export) are registered before parameterized ones (e.g. /staff/:id)
// Otherwise GET /staff/export would match /staff/:id with id="export"
registrations.sort((a, b) => {
  const sortKey = (p) => p.replace(/:[a-zA-Z]+/g, () => '\uffff'); // :param -> high char so literals sort first
  return sortKey(a.routePath).localeCompare(sortKey(b.routePath));
});

const content = `/** Auto-generated by scripts/gen-routes.mjs - DO NOT EDIT */
import type { Express } from 'express';
import { adaptNextRoute } from './adaptNextRoute.js';
import { authMiddleware } from './lib/authMiddleware.js';

${imports.join('\n')}

export function registerRoutes(app: Express) {
${registrations.map((r) => r.line).join('\n')}
}
`;

fs.writeFileSync(outFile, content);
console.log(`Generated ${outFile} with ${registrations.length} route registrations`);
