/**
 * Generates src/routes.generated.ts from the api folder structure.
 * Run: npx tsx scripts/generate-routes.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const apiDir = path.join(__dirname, '../src/api');

const methods = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const;

function findRouteFiles(dir: string, base = ''): { routePath: string; filePath: string }[] {
  const results: { routePath: string; filePath: string }[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = base ? `${base}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      results.push(...findRouteFiles(fullPath, relPath));
    } else if (entry.name === 'route.ts') {
      const routePath = '/api/' + relPath.replace(/\/route\.ts$/, '').replace(/\[([^\]]+)\]/g, ':$1');
      results.push({ routePath, filePath: fullPath });
    }
  }
  return results;
}

function getExportedMethods(filePath: string): typeof methods[number][] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const found: typeof methods[number][] = [];
  for (const m of methods) {
    if (new RegExp(`export\\s+async\\s+function\\s+${m}\\s*\\(`).test(content)) found.push(m);
  }
  return found;
}

const routeFiles = findRouteFiles(apiDir);
const lines: string[] = [
  `/** Auto-generated by scripts/generate-routes.ts - DO NOT EDIT */`,
  `import { adaptNextRoute } from './adaptNextRoute.js';`,
  ``,
];

for (const { routePath, filePath } of routeFiles) {
  const relImport = path.relative(path.join(__dirname, '../src'), filePath).replace(/\.ts$/, '.js').replace(/\\/g, '/');
  const exported = getExportedMethods(filePath);
  for (const method of exported) {
    const m = method.toLowerCase();
    lines.push(`import * as _${m.replace(/[^a-z0-9]/g, '_')}_${routePath.replace(/\//g, '_').replace(/[^a-z0-9_]/g, '')} from './${relImport}';`);
  }
}

lines.push('');
lines.push('export function registerRoutes(app: import("express").Express) {');
lines.push('  const a = (h: (r: Request) => Promise<Response>) => adaptNextRoute(h);');
lines.push('');

for (const { routePath, filePath } of routeFiles) {
  const relImport = path.relative(path.join(__dirname, '../src'), filePath).replace(/\.ts$/, '.js').replace(/\\/g, '/');
  const exported = getExportedMethods(filePath);
  const varName = '_' + routePath.replace(/\//g, '_').replace(/[^a-z0-9_]/g, '') + '_';
  for (const method of exported) {
    const m = method.toLowerCase();
    lines.push(`  app.${m}('${routePath}', a((await import('./${relImport}')).${method}));`);
  }
}

lines.push('}');

// Fix: we need to use sync imports for the registration. Let me simplify - use require-style.
// Actually the issue is we're mixing await import in a non-async function. Let me change to static imports.
// The generated file would have 100+ import lines and 100+ app.get/post lines. Let me regenerate with static imports.
</think>

<｜tool▁calls▁begin｜><｜tool▁call▁begin｜>
Read