/** Seed data for discount codes - used by seed script and API */

const now = new Date();
const in30Days = new Date(now);
in30Days.setDate(in30Days.getDate() + 30);
const in90Days = new Date(now);
in90Days.setDate(in90Days.getDate() + 90);
const in180Days = new Date(now);
in180Days.setDate(in180Days.getDate() + 180);

export const DISCOUNT_CODE_SEED = [
  {
    code: 'WELCOME10',
    type: 'percent' as const,
    value: 10,
    minAmount: 1000,
    maxDiscountAmount: 250,
    maxUses: 500,
    validFrom: now,
    validUntil: in180Days,
    description: 'Welcome discount for new parents (max ₹250)',
    applicableBoards: [],
    applicableClasses: [],
  },
  {
    code: 'SUMMER20',
    type: 'percent' as const,
    value: 20,
    minAmount: 2000,
    maxDiscountAmount: 500,
    maxUses: 200,
    validFrom: now,
    validUntil: in90Days,
    description: 'Summer special - 20% off (max ₹500)',
    applicableBoards: [],
    applicableClasses: [],
  },
  {
    code: 'FLAT500',
    type: 'fixed' as const,
    value: 500,
    minAmount: 3000,
    maxUses: 100,
    validFrom: now,
    validUntil: in90Days,
    description: 'Flat ₹500 off on orders above ₹3000',
    applicableBoards: [],
    applicableClasses: [],
  },
  {
    code: 'CBSE15',
    type: 'percent' as const,
    value: 15,
    minAmount: 1500,
    maxDiscountAmount: 400,
    maxUses: 150,
    validFrom: now,
    validUntil: in180Days,
    description: 'CBSE board special (max ₹400)',
    applicableBoards: ['CBSE'],
    applicableClasses: [],
  },
  {
    code: 'CLASS5',
    type: 'percent' as const,
    value: 12,
    minAmount: 1200,
    maxDiscountAmount: 300,
    maxUses: 80,
    validFrom: now,
    validUntil: in90Days,
    description: 'Class 5 special offer (max ₹300)',
    applicableBoards: [],
    applicableClasses: ['5'],
  },
  {
    code: 'EARLYBIRD',
    type: 'percent' as const,
    value: 15,
    minAmount: 2500,
    maxDiscountAmount: 600,
    maxUses: 100,
    validFrom: now,
    validUntil: in30Days,
    description: 'Early bird - 15% off for 12-month plans (max ₹600)',
    applicableBoards: [],
    applicableClasses: [],
  },
  {
    code: 'REFER50',
    type: 'fixed' as const,
    value: 250,
    minAmount: 0,
    maxUses: 300,
    validFrom: now,
    validUntil: in180Days,
    description: 'Referral bonus - ₹250 off',
    applicableBoards: [],
    applicableClasses: [],
  },
  {
    code: 'BACK2SCHOOL',
    type: 'percent' as const,
    value: 18,
    minAmount: 1800,
    maxDiscountAmount: 450,
    maxUses: 120,
    validFrom: now,
    validUntil: in90Days,
    description: 'Back to school special (max ₹450)',
    applicableBoards: [],
    applicableClasses: [],
  },
];
